# Site settings
title: Hyeonjin kim
email: kimhj9502@gmail.com
url: https://chulbal.github.io
description: " Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "keywords, separated by commas"
skills: "Psychiatry - Computational Modeling - Neuroscience"
meta_author: Kim Hyeonjin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 607D8B # Head and About
  primary-light: CFD8DC
  primary-rgb: "96,125,139" #"128,179,255"
  secondary: 37474F # The top bar color (dark)
  secondary-dark: 263238 # Location foot color
  secondary-light: ECEFF1

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hjinworld
  - title: github
    url: http://github.com/ChulBal

# Postal address (add as many lines as necessary)
address:
  - line: 1, Gwanak-ro, Gwanak-gu 
  - line: Seoul, Republic of Korea

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
